//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhuKienDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDonBan
    {
        public int MaHoaDonBan { get; set; }
        public int MaSanPham { get; set; }
        public string GhiChu { get; set; }
        public int SoLuongBan { get; set; }
        public int MaHoaDonBanChiTiet { get; set; }
    
        public virtual HoaDonBan HoaDonBan { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
