//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhuKienDienTu
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        public int MaTaiKhoan { get; set; }
        public int MaNhanVien { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
