
create database QuanLyDienMay
use QuanLyDienMay
go 
CREATE TABLE Product
(
	IDProduct INT IDENTITY(1,1)
	CONSTRAINT PK_IDProduct PRIMARY KEY,
	IDBranch INT NOT NULL DEFAULT 1,
	IDType INT NOT NULL DEFAULT 1,
	Name NVARCHAR(100) NOT NULL,
	Color NVARCHAR(50) NOT NULL,
	Description NVARCHAR(300) NOT NULL,
	PriceOut DECIMAL(19, 4) DEFAULT 1000,
	PriceIn DECIMAL(19, 4) DEFAULT 1000,
	WarrantyTime FLOAT NOT NULL
)

go

CREATE TABLE Type
 (
	IDType INT IDENTITY(1,1)
	CONSTRAINT PK_IDType PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL
)

go

CREATE TABLE Client
 (
	IDClient INT IDENTITY(1,1)
	CONSTRAINT PK_IDClient PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Address NVARCHAR(100) NOT NULL,
	Phone NVARCHAR(50) NOT NULL
	
)

go 
CREATE TABLE Branch
(
	IDBranch INT IDENTITY(1,1)
	CONSTRAINT PK_IDBranch PRIMARY KEY,
	Name NVARCHAR(100) NOT NULL,
	Origin NVARCHAR(50) NOT NULL
)


go
CREATE TABLE Staff
(
	IDStaff INT IDENTITY(1,1)
		CONSTRAINT PK_IDStaff PRIMARY KEY,
	Status INT NOT NULL DEFAULT 0,
	Name NVARCHAR(50) NOT NULL,
	Address NVARCHAR(100),
	Phone NVARCHAR(50) NOT NULL
)

go

CREATE TABLE Account 
(
	IDAccount INT IDENTITY(1,1)
		CONSTRAINT PK_IDAccount PRIMARY KEY,
	IDStaff INT NOT NULL,
	Username NVARCHAR(50) NOT NULL,
	Password NVARCHAR(50) NOT NULL
)

go

CREATE TABLE Bill
(	
	IDBill INT IDENTITY(1,1)
		CONSTRAINT PK_IDBill PRIMARY KEY,
	IDClient INT NOT NULL DEFAULT 1,
	DateOut DATETIME NOT NULL
	
)

go

CREATE TABLE BillInfo
(	IDBill INT NOT NULL DEFAULT 1,
	IDProduct INT NOT NULL DEFAULT 1,
	Amount INT DEFAULT 0
)

go

ALTER TABLE Account
ADD CONSTRAINT FK_Account_IDStaff
	FOREIGN KEY (IDStaff)
	REFERENCES Staff(IDStaff)
	ON UPDATE CASCADE

ALTER TABLE Bill
ADD CONSTRAINT FK_Bill_IDClient
	FOREIGN KEY (IDClient)
	REFERENCES Client(IDClient)
	ON UPDATE CASCADE


go

ALTER TABLE Product
ADD CONSTRAINT FK_Product_IDBranch
	FOREIGN KEY (IDBranch)
	REFERENCES Branch(IDBranch),

	CONSTRAINT FK_Product_IDType
	FOREIGN KEY (IDType)
	REFERENCES TYPE(IDType)


go
ALTER TABLE BillInfo
ADD CONSTRAINT FK_BillInfo_IDProduct
	FOREIGN KEY (IDProduct)
	REFERENCES Product(IDProduct)
	ON UPDATE CASCADE,

	CONSTRAINT FK_BillInfo_IDBill
	FOREIGN KEY (IDBill)
	REFERENCES Bill(IDBill)
	ON UPDATE CASCADE

	
